import type { QueryRunner } from "../../core/discovery/relationships";
import { quoteIdent } from "../../core/sql/sql-utils";
import type { ColumnInfo, TableInfo } from "../../core/types";
import { sanitizeTableName } from "../../core/utils";
import { ATTACH_TYPE, type AttachSpec } from "./connection-string";

/** The alias the external database is attached under. */
const ATTACH_ALIAS = "__src";

/** Schemas that carry engine internals rather than user data. */
const SYSTEM_SCHEMAS = new Set([
  "information_schema",
  "pg_catalog",
  "pg_toast",
  "mysql",
  "performance_schema",
  "sys",
]);

export interface AttachLoadOptions {
  /** Restrict discovery to one schema (e.g. `public`). */
  schema?: string;
  /** Cap how many tables are registered; the rest are reported as skipped. */
  maxTables?: number;
}

export interface AttachLoadResult {
  tables: TableInfo[];
  /** Tables present in the source but not registered (system schema or over the cap). */
  skipped: string[];
}

function escapeLiteral(value: string): string {
  return value.replaceAll("'", "''");
}

/** Ensure a view name is unique when two schemas expose the same table name. */
function uniqueName(base: string, taken: Set<string>): string {
  if (!taken.has(base)) {
    taken.add(base);
    return base;
  }
  let suffix = 2;
  while (taken.has(`${base}_${suffix}`)) suffix += 1;
  const name = `${base}_${suffix}`;
  taken.add(name);
  return name;
}

async function describeView(name: string, runner: QueryRunner): Promise<ColumnInfo[]> {
  const rows = await runner(`DESCRIBE ${quoteIdent(name)}`);
  return rows.map((row) => ({
    name: String(row.column_name),
    type: String(row.column_type),
  }));
}

async function countRows(name: string, runner: QueryRunner): Promise<number> {
  const rows = await runner(`SELECT COUNT(*) AS cnt FROM ${quoteIdent(name)}`);
  return Number(rows[0]?.cnt ?? 0);
}

/**
 * Attach an external database read-only and expose each of its tables as a local
 * view, so the engine-agnostic discovery core runs against a live Postgres/MySQL/
 * SQLite exactly as it does over a folder of files.
 *
 * Views (not tables) on purpose: nothing is copied into memory and profiling /
 * value-overlap queries push down to the source engine.
 *
 * DuckDB enforces the read-only attachment itself, so no statement issued by
 * QueryPad — or generated by the agent — can modify the source database.
 */
export async function attachDatabase(
  spec: AttachSpec,
  runner: QueryRunner,
  options: AttachLoadOptions = {}
): Promise<AttachLoadResult> {
  await runner(
    `ATTACH '${escapeLiteral(spec.target)}' AS ${quoteIdent(ATTACH_ALIAS)} ` +
      `(TYPE ${ATTACH_TYPE[spec.engine]}, READ_ONLY)`
  );

  const rows = await runner(
    `SELECT schema_name, table_name FROM duckdb_tables() ` +
      `WHERE database_name = '${escapeLiteral(ATTACH_ALIAS)}' ` +
      `ORDER BY schema_name, table_name`
  );

  const tables: TableInfo[] = [];
  const skipped: string[] = [];
  const taken = new Set<string>();
  const multiSchema = new Set(rows.map((row) => String(row.schema_name))).size > 1;

  for (const row of rows) {
    const schema = String(row.schema_name);
    const table = String(row.table_name);
    const qualified = `${schema}.${table}`;

    if (SYSTEM_SCHEMAS.has(schema.toLowerCase())) continue;
    if (options.schema && schema !== options.schema) continue;
    if (options.maxTables !== undefined && tables.length >= options.maxTables) {
      skipped.push(qualified);
      continue;
    }

    // Prefix the local name with the schema only when schemas would collide.
    const base = sanitizeTableName(multiSchema && !options.schema ? qualified : table);
    const name = uniqueName(base, taken);

    await runner(
      `CREATE OR REPLACE VIEW ${quoteIdent(name)} AS SELECT * FROM ` +
        `${quoteIdent(ATTACH_ALIAS)}.${quoteIdent(schema)}.${quoteIdent(table)}`
    );
    tables.push({
      name,
      columns: await describeView(name, runner),
      rowCount: await countRows(name, runner),
    });
  }

  return { tables, skipped };
}
